version: "3.9"

services:
  service-registry:
    image: sahilparekh/service-registry:latest
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  config-server:
    image: sahilparekh/config-server:latest
    container_name: config-server
    ports:
      - "9296:9296"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    depends_on:
      - mysql

  api-gateway:
    image: sahilparekh/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    depends_on:
      - service-registry
      - config-server

  authentication-service:
    image: sahilparekh/authentication-service:latest
    container_name: authentication-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    depends_on:
      - service-registry
      - config-server
      - mysql

  user-service:
    image: sahilparekh/user-service:latest
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    depends_on:
      - service-registry
      - config-server
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rest_api
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
