server:
  port: 8080
logging:
  level:
    io:
      github:
        resilience4j: DEBUG
    org:
      springframework:
        - security: DEBUG
        - security:
            web: DEBUG
        - cloud:
            gateway: DEBUG
        - web: DEBUG

debug: true
spring:
  security:
    csrf:
      enabled: false
  application:
    name: ApiGateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  config:
    import: "configserver:http://localhost:9296"
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/users/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: UserService
                fallbackUri: forward:/userServiceFallback
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/authenticate/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: AuthenticationService
                fallbackUri: forward:/authServiceFallback