server:
  port: 8082

spring:
  application:
    name: AuthenticationService
  profiles:
    active: prod

eureka:
  client:
    service-url:
      defaultZone: http://api-gateway:8761/eureka/
    register-with-eureka: true
    fetch-registry: true