server:
  port: 8082

logging:
  level:
    org:
      springframework:
        - security: DEBUG
        - security:
            web:
              csrf: DEBUG
        - cloud:
            gateway: DEBUG
        - web: DEBUG

debug: true
spring:
  application:
    name: AuthenticationService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true