server:
  port: 8761

spring:
  application:
    name: ServiceRegistry

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: WARN
    com.netflix.eureka: INFO # Log only important Eureka-related events