server:
  port: 8081

spring:
  application:
    name: UserService
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://mysql:3307/rest_api
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "configserver:http://config-server:9296"

eureka:
  client:
    service-url:
      defaultZone: http://api-gateway:8761/eureka/
    register-with-eureka: true
    fetch-registry: true